# Generated by Django 4.1.3 on 2022-11-25 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='filter_history',
            new_name='filter',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_order_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='filter_option',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='order',
            name='filter_option',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.filter_option'),
        ),
    ]
