# Generated by Django 4.1.3 on 2022-11-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
        ('users', '0002_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='filter_option',
        ),
        migrations.AddField(
            model_name='user',
            name='asd',
            field=models.ManyToManyField(related_name='asd', to='store.filter_option'),
        ),
    ]
