# Generated by Django 4.1.3 on 2022-11-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageStorage', '0002_initial'),
        ('users', '0002_alter_order_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ImageStorage.image'),
        ),
    ]
