# Generated by Django 4.1.3 on 2022-11-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
        ('users', '0003_remove_user_filter_option_user_asd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='asd',
        ),
        migrations.AddField(
            model_name='user',
            name='my_option',
            field=models.ManyToManyField(related_name='my_option_filter', to='store.filter_option'),
        ),
    ]
