# Generated by Django 4.1.3 on 2022-11-23 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userfilterbookmark_filter_bookmark'),
        ('users', '0004_alter_user_address_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='filter_option',
        ),
        migrations.CreateModel(
            name='FilterOptionCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cart')),
                ('filter_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.filter_option')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='filter_option',
            field=models.ManyToManyField(through='users.FilterOptionCart', to='store.filter_option'),
        ),
    ]
