# Generated by Django 4.1.3 on 2022-11-25 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filter_option',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.filter'),
        ),
        migrations.AddField(
            model_name='filter',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmark_filter', to=settings.AUTH_USER_MODEL),
        ),
    ]
