# Generated by Django 4.1.3 on 2022-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='filter_option',
            name='type',
            field=models.CharField(choices=[('ALBUM', 'Album'), ('PHOTOCARD', 'Photocard'), ('STICKER', 'Sticker'), ('LETTER', 'Letter'), ('CALENDAR', 'Calendar')], max_length=100),
        ),
    ]
