# Generated by Django 4.1.3 on 2022-11-22 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilterBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.filter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='bookmark',
            field=models.ManyToManyField(through='store.UserFilterBookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
