# Generated by Django 4.1.3 on 2022-11-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_filter_filter_name_alter_filter_option_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter_option',
            name='type',
        ),
    ]
