# Generated by Django 4.1.3 on 2022-11-23 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_userfilterbookmark_filter_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmark_filter', through='store.UserFilterBookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.filter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='user',
            field=models.ManyToManyField(related_name='user_filter', through='store.UserFilter', to=settings.AUTH_USER_MODEL),
        ),
    ]
