# Generated by Django 4.1.3 on 2022-11-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageStorage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='input_img',
            field=models.FileField(default=None, null=None, upload_to='input/', verbose_name='입력사진'),
        ),
        migrations.AddField(
            model_name='image',
            name='output_img',
            field=models.FileField(default=None, null=None, upload_to='output/', verbose_name='결과사진'),
        ),
    ]
