# Generated by Django 4.1.3 on 2022-11-24 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ImageStorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.filter'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
