# Generated by Django 4.1.3 on 2022-11-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ImageStorage", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="filter",
            new_name="filters",
        ),
    ]
