# Generated by Django 4.1.6 on 2023-02-07 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ImageStorage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='likes_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
