# Generated by Django 4.1.3 on 2022-11-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ImageStorage", "0003_rename_filter_image_filters"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="filters",
            new_name="filter",
        ),
    ]
